apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fg3y7pm57-python
  janus-idp.io/tekton: fg3y7pm57-python
  backstage.io/kubernetes-id: fg3y7pm57-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fg3y7pm57-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
